### ISSUE TITLE
Alfred版本使用问题

### ISSUE THREAD

**Issue by Elvins** [jaywcjlove/linux-command#74]
显示 Couldn't find the 'node' binary
symlink it to /usr/local/bin

请问这个是什么原因，如何解决？

**Comment by jaywcjlove** [comment]
@Elvins 不知道你安装的什么版本。

**Comment by Elvins** [comment]
Linux.Command.alfredworkflow
v1.0.0那个

**Comment by jaywcjlove** [comment]
@Elvins 是不是要安装 `node.js` ?

**Comment by Elvins** [comment]
> @Elvins 是不是要安装 `node.js` ?

@jaywcjlove 
找到问题了，是没有安装node.js。
另外，请问那个v1.3.0的版本是怎么安装的?也没有workflow

**Comment by fliu2476** [comment]
> @Elvins 是不是要安装 `node.js` ?

遇到同样的问题，是因为使用```nvm```管理node版本，导致```/usr/local/bin```下没有node，用命令查看node位置:
```
xxxx:/ xxxx$ which node
/Users/xxxx/.nvm/versions/node/v10.15.3/bin/node
```
然后去Alfred里编辑这个workflow，替换引用的node位置就ok了

**Comment by jaywcjlove** [comment]
> > @Elvins 是不是要安装 `node.js` ?
> 
> 遇到同样的问题，是因为使用`nvm`管理node版本，导致`/usr/local/bin`下没有node，用命令查看node位置:
> 
> ```
> xxxx:/ xxxx$ which node
> /Users/xxxx/.nvm/versions/node/v10.15.3/bin/node
> ```
> 
> 然后去Alfred里编辑这个workflow，替换引用的node位置就ok了


我是用的 [n](https://github.com/tj/n) 管理 node.js 的， nvm 是有这个问题。我之前用 nvm 后来换回  [n](https://github.com/tj/n) 了。 

```bash
▶ which node
/usr/local/bin/node
```

**Comment by guiqide** [comment]
> > @Elvins 是不是要安装 `node.js` ?
> 
> 遇到同样的问题，是因为使用`nvm`管理node版本，导致`/usr/local/bin`下没有node，用命令查看node位置:
> 
> ```
> xxxx:/ xxxx$ which node
> /Users/xxxx/.nvm/versions/node/v10.15.3/bin/node
> ```
> 
> 然后去Alfred里编辑这个workflow，替换引用的node位置就ok了

使用该方法，解决下面的问题，
```
[2019-04-28 14:24:30][ERROR: input.scriptfilter] Code 134: dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.60.dylib
Referenced from: /usr/local/bin/node
Reason: image not found
/bin/bash: line 2: 80451 Abort trap: 6 /usr/local/bin/node <<-'CODE'
require("./linux")("c");
CODE
```

**Comment by jaywcjlove** [comment]
@guiqide 极有可能是  `nvm` 导致的问题，可以通过管理工具 [`https://github.com/tj/n`] 替代 `nvm` 来解决，或者重新安装 node.js 试一试。

```bash
brew uninstall --force node && brew install node
```

**Comment by jaywcjlove** [comment]
![image](https://user-images.githubusercontent.com/1680273/57190606-989bf280-6f4e-11e9-9da4-9040fa720e19.png)
看一下你的 node 命令的位置 `/usr/local/bin/node`

**Comment by guiqide** [comment]
@jaywcjlove 谢谢，我的评论说明了，已经修复了。
建议这里的bash命令不要写死固定路径。

**Comment by jaywcjlove** [comment]
@guiqide 由 [**@SHANG殇**](https://github.com/xinshangshangxin) 提供的 `Dash` 版本 [#91](https://github.com/jaywcjlove/linux-command/pull/91)，可配合 `alfred` 玩耍，下载 [linux-command.docset.zip](https://github.com/jaywcjlove/linux-command/releases) 文件解压，点击安装即可，不需要安装 `node.js`。

[![](https://user-images.githubusercontent.com/8779091/57193499-5b475d00-6f6e-11e9-879d-e7e8fdc40ced.gif)](https://github.com/jaywcjlove/linux-command/releases)

**Comment by xinshangshangxin** [comment]
配合 alfred 玩耍 补充2点

1: 在 `alfred` 中使用  `dash` 需要先导入 `dash` 的 `workflow`
![image](https://user-images.githubusercontent.com/8779091/57194583-1bd33d80-6f7b-11e9-9c7d-89609ab1be23.png)

2: `linux-command`输入太长, 修改关键字/keyword (比如输入 `lc`)
![image](https://user-images.githubusercontent.com/8779091/57194618-74a2d600-6f7b-11e9-82a2-3686bebf0efe.png)

**Comment by guiqide** [comment]
@xinshangshangxin @jaywcjlove  两个都尝试了一下，都不错👍。不过对比alfred版可以直接看到命令的概述更符合个人的使用习惯

**Comment by wqwangwei** [comment]
workflow这个alfred的插件文件在哪里,我下载解压完没有找到插件文件~具体怎么用求指教

**Comment by xinshangshangxin** [comment]
> workflow这个alfred的插件文件在哪里,我下载解压完没有找到插件文件~具体怎么用求指教

下载老版本, 新版本代码没有build 成 dash的 `linux-command.docset`
https://github.com/jaywcjlove/linux-command/issues/74#issuecomment-489423491

@jaywcjlove 建议搞个 `Github Actions`, 每次发版自动build一个并且 releas?

**Comment by jaywcjlove** [comment]
@xinshangshangxin 了解，如果有PR 最好了，我需要研究一下，现在 Github Actions 自动 发布 web 版本，还不知道怎么 released。

**Comment by wqwangwei** [comment]
@xinshangshangxin 那个版本有,我下载好几个版本都没有

**Comment by xinshangshangxin** [comment]
> @xinshangshangxin 那个版本有,我下载好几个版本都没有

https://github.com/jaywcjlove/linux-command/releases/tag/v1.2.2

![image](https://user-images.githubusercontent.com/8779091/69841767-804d4580-129b-11ea-80ce-bf1d7b64a2e1.png)

**Comment by wqwangwei** [comment]
@xinshangshangxin 谢谢帮助~也给不知道插件的小伙伴打个样~~~下载插件去https://github.com/jaywcjlove/linux-command/releases/tag/v1.2.2

**Comment by xinshangshangxin** [comment]
> @xinshangshangxin 了解，如果有PR 最好了，我需要研究一下，现在 Github Actions 自动 发布 web 版本，还不知道怎么 released。

@jaywcjlove 
如果还没有开始研究的话, 近期我看看能不能做一个

**Comment by grchen** [comment]
怎么编译docset？

**Comment by jaywcjlove** [comment]
@grchen 在跟目录运行下面命令

```bash
$ npm install 
$ npm run dash
```

**Comment by Icedroid** [comment]
❯ npm install
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../lib/utils/unsupported.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:19:21
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:153:3)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)

**Comment by JiangJiaWei520** [comment]
有人帮忙解答下吗  
鈫?\.deploy\c\zipinfo.html
  鈫?\.deploy\c\zipsplit.html
  鈫?\.deploy\c\znew.html
mkdir -p D:\GitHub\linux-command\.deploy\linux-command.docset/Contents/Resources/
========= do clean =========
build resources...
Error: Source and destination must not be the same.
    at D:\GitHub\linux-command\node_modules\fs-extra\lib\util\stat.js:39:17
    at cb (util.js:207:31)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by xiangbohua** [comment]
/usr/local/bin/node <<-'CODE'
require("./linux")("{query}");
CODE

想知道这段代码的含义，机器上面没有node 想用php或者py替代一下，可行吗？

**Comment by jaywcjlove** [comment]
@xiangbohua 给予 node 开发的。需要安装 `nodejs`

**Comment by xiangbohua** [comment]
> @xiangbohua 给予 node 开发的。需要安装 `nodejs`

在研究了一会，发现这个js应该是用来展示搜索结果的，如果没有这个东西的话，就只能直接打开网站的地址，如果找不到就会报错，我再翻翻你们的代码，自己看看能不能改一个php版本，实在不想碰node.

**Comment by jaywcjlove** [comment]
@xiangbohua 欢迎提交更多的支持。

**Comment by xiangbohua** [comment]
> > @xiangbohua 给予 node 开发的。需要安装 `nodejs`
> 
> 在研究了一会，发现这个js应该是用来展示搜索结果的，如果没有这个东西的话，就只能直接打开网站的地址，如果找不到就会报错，我再翻翻你们的代码，自己看看能不能改一个php版本，实在不想碰node.

我又看了一会发现好像就是本地js....

**Comment by xiangbohua** [comment]
我本来以为命令的数据库是放在server上，通过{query}可以请求到可选的list，但是如果是页面加载了完整的js文件的话，就只能把文件down到本地然后再搜索，就没办法更新了。
dead road ⏏

**Comment by iT-Boyer** [comment]
> @grchen 在跟目录运行下面命令
> 
> ```shell
> $ npm install 
> $ npm run dash
> ```

支持生成Alfred版本吗？

**Comment by tiandee** [comment]
> 
使用mac的话，brew install node即可
